article/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = "article"

urlpatterns = [
    path("",views.index,name = "index"),
    path("registro/",views.registro, name="registro"),
    path("iniciar_sesion/", views.iniciar_sesion, name="iniciar_sesion"),
    path("cerrar_sesion/", views.cerrar_sesion, name="cerrar_sesion"),
    path("<int:id>/ver_articulo/", views.ver_articulo, name="ver_articulo"),
    path("crear_articulo/", views.crear_articulo, name="crear_articulo"),
    path("registro_exitoso", views.registro_exitoso, name="registro_exitoso"),
    path("<int:id>", views.dar_heart, name="dar_heart"),
]

prueba/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("article.urls"))
]

article/models.py
from django.db import models
from django.forms import CharField
from django.contrib.auth.models import User


class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    photo = models.CharField(max_length=300)

class Article(models.Model):
    title = models.CharField(max_length=1000)
    author_fk = models.ForeignKey(UserProfile, on_delete=models.CASCADE)
    text = models.CharField(max_length=1000)
    image = models.CharField(max_length=1000)
    date = models.DateField()
    hearts = models.IntegerField()

class Comment(models.Model):
    author_fk = models.ForeignKey(UserProfile, on_delete=models.CASCADE)
    text = models.CharField(max_length=1000)
    publicacion_fk = models.ForeignKey(Article, on_delete=models.CASCADE)

class Comment_second_level(models.Model):
    author_fk = models.ForeignKey(UserProfile,on_delete=models.CASCADE)
    text = models.CharField(max_length=1000)
    comentario_fk = models.ForeignKey(Comment, on_delete=models.CASCADE)

    
    

article/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import authenticate
from django.contrib.auth.models import User


class RegistroForm(UserCreationForm):
  
    class Meta():
        model = User
        fields = ("username", "email", "password1","password2")
        labels = {"username":"Nombre completo", "email": "Correo","password1":"Ingrese contraseña","password2":"Confirme contraseña"}

class AutheticateForm(forms.ModelForm):

    password = forms.CharField(label="Contraseña", widget=forms.PasswordInput)

    def clean(self):
        email = self.cleaned_data["email"]
        password = self.cleaned_date["password"]

        if not authenticate(email=email, password=password):
            raise forms.ValidationError("El email o la contraseña son incorrectos")

article/views.py
from cmath import phase
from pyexpat.errors import messages
from unicodedata import name
from django.shortcuts import redirect, render, get_object_or_404
from .models import *
from django.contrib.auth import login, logout, authenticate
from .forms import RegistroForm
from datetime import datetime

def index(request):
    articulos = Article.objects.all()
    return render(request, "article/index.html",{"articles":articulos})

def registro(request):
    data = {
        'form' : RegistroForm()
    }
    if request.method == 'POST':
        formulario = RegistroForm(request.POST)
        if formulario.is_valid():
            user_save = formulario.save()
            username1 = formulario.cleaned_data["username"]
            password1 = formulario.cleaned_data["password1"]
            user = UserProfile(user=user_save, photo=request.POST.get('photo'))
            user.save()
            user = authenticate(username=username1, password=password1)
            login(request, user)
            return redirect("/")
        data['form'] = formulario

    return render(request, "article/registro.html",data)

def iniciar_sesion(request):
    if request.method == 'POST':
        username1 = request.POST.get('username')
        password1 = request.POST.get('password')
        usuario = authenticate(username=username1, password = password1)
        if usuario is not None:
            login(request, usuario)
            return redirect("/")
        
    return render(request, "article/iniciar_sesion.html")

def cerrar_sesion(request):
    logout(request)
    return redirect("/")

def ver_articulo(request, id):
    articulo = Article.objects.get(pk=id)
    comentarios = Comment.objects.filter(publicacion_fk_id=id)
    if request.method == 'POST':
        author = articulo.author_fk
        texto = request.POST.get('texto')
        comentario = Comment(author_fk=author,text =texto,publicacion_fk=articulo)
        comentario.save()
        redirect("article/ver_articulo.html",{"articulo":articulo})
    return render(request, "article/ver_articulo.html", {"articulo":articulo,"comentarios":comentarios})



def crear_articulo(request):
    id_usuario = request.session['_auth_user_id']
    if request.method == 'POST':
        titulo = request.POST.get("titulo")
        texto = request.POST.get('texto')
        foto = request.POST.get('foto')
        author = UserProfile.objects.get(user_id=id_usuario)
        fecha = datetime.now()
        art = Article(title=titulo,author_fk=author,text=texto,image=foto,date=fecha,hearts=0)
        art.save()
        comment = Comment(author_fk=author, text="Comentario necesario",publicacion_fk=art)
        comment.save()
        second_comment = Comment_second_level(author_fk=author, text="Comentario necesario",comentario_fk=comment)
        second_comment.save()
        return redirect("/")
    return render(request, "article/crear_articulo.html",{})

def registro_exitoso(request):
    return render(request, "article/registro_exitoso.html",{})

def dar_heart(request, id):
    user = request.user.id
    print(user)
    seleccionado = get_object_or_404(Article, pk=id)
    seleccionado.hearts = seleccionado.hearts+1
    seleccionado.save()
    return redirect("/")

article/templates/article/crear_articulo.html
<html>
  <head>
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3"
      crossorigin="anonymous"
    />
    <title>Crear articulo</title>
  </head>
  <body>
    <header>
      <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="#">Hackers blog</a>
        <button
          class="navbar-toggler"
          type="button"
          data-toggle="collapse"
          data-target="#navbarNavDropdown"
          aria-controls="navbarNavDropdown"
          aria-expanded="false"
          aria-label="Toggle navigation"
        >
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
          <ul class="navbar-nav">
            <li class="nav-item active">
              <a class="nav-link" href="#"
                >Bienvenido al registro de tu articulo
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Sesión de {{ user.get_username }} </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#"></a>
            </li>
          </ul>
        </div>
      </nav>
    </header>
    <br><br>
    <main>
        <form method="post" action="{% url 'article:crear_articulo' %}">
            {% csrf_token %} 
            <div class="container">
        <div class="input-group mb-3">
            <div class="input-group-prepend">
              <span class="input-group-text" id="inputGroup-sizing-default">Titulo</span>
            </div>
            <input type="text" name="titulo" class="form-control" aria-label="Default" aria-describedby="inputGroup-sizing-default">
          </div>
        <textarea name="texto"rows="10" cols="50"> </textarea> <br><br>
        <div class="input-group mb-3">
            <div class="input-group-prepend">
              <span class="input-group-text" id="inputGroup-sizing-default">Foto del articulo (url)</span>
            </div>
            <input name="foto" type="text" class="form-control" aria-label="Default" aria-describedby="inputGroup-sizing-default">
          </div>
          <button type="submit" class="btn btn-primary">Enviar</button>
        </form>
    </main>

    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
      crossorigin="anonymous"
    ></script>
  </body>
</html>

article/templates/article/index.html
<html>
  <head>
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3"
      crossorigin="anonymous"
    />
    <title>Hacker's blog</title>
  </head>

  <body>
    <header>
      <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">
          <a class="navbar-brand" href="#">Hacker's blog</a>
          <button
            class="navbar-toggler"
            type="button"
            data-bs-toggle="collapse"
            data-bs-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent"
            aria-expanded="false"
            aria-label="Toggle navigation"
          >
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="#"
                  >Inicio</a
                >
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'article:crear_articulo' %}"
                  >Registrar articulo</a
                >
              </li>
              <li class="nav-item dropdown">
                <a
                  class="nav-link dropdown-toggle"
                  href="#"
                  id="navbarDropdown"
                  role="button"
                  data-bs-toggle="dropdown"
                  aria-expanded="false"
                >
                  {% if user.is_authenticated %} 
                    {{ user.get_username }} 
                  {% else %} 
                  Sesión 
                  {% endif %}
                </a>
                <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                  {% if user.is_authenticated %}
                  <li>
                    <a
                      class="dropdown-item"
                      href="{% url 'article:cerrar_sesion' %}"
                      >Cerrar sesion</a
                    >
                  </li>
                  {% else %}
                  <li>
                    <a
                      class="dropdown-item"
                      href="{% url 'article:iniciar_sesion' %}"
                      >Ingresar</a
                    >
                  </li>
                  <li><hr class="dropdown-divider" /></li>
                  <li>
                    <a class="dropdown-item" href="{% url 'article:registro' %}"
                      >Registrarse</a
                    >
                  </li>
                  {% endif%}
                </ul>
              </li>
            </ul>

            <form class="d-flex">
              <input
                class="form-control me-2"
                type="search"
                placeholder="Ingrese texto"
                aria-label="Search"
              />
              <button class="btn btn-outline-success" type="submit">
                Buscar
              </button>
            </form>
          </div>
        </div>
      </nav>
    </header>

    <br />

    <main>
      <div class="d-flex flex-row" >
        {% for article in articles %}
        <div class="card col-sm-6" style="width: 18rem; margin:0.5em">
          <img
            class="card-img-top"
            src="{{ article.image }}"
            alt="Card image cap"
          />
          <div class="card-body">
            <h5 class="card-title">{{ article.title }}</h5>
            <p class="card-text">{{ article.text }}</p>
            <ul class="list-group list-group-flush">
              <li class="list-group-item">
                Author: {{ article.author_fk.user.username }}
              </li>
              <li class="list-group-item">Date published: {{article.date}}</li>
              <li class="list-group-item">Hearts: {{ article.hearts }}</li>
            </ul>
            <a
              href="{% url 'article:ver_articulo' article.id %}"
              class="btn btn-primary"
              >Ver</a
            >
            <a
              href="{% url 'article:dar_heart' article.id %}"
              class="btn btn-primary"
              >Heart++</a
            >
          </div>
        </div>
        {% endfor %}
      </div>
    </main>

    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
      crossorigin="anonymous"
    ></script>
  </body>
</html>

article/templates/article/iniciar_sesion.html
{% load widget_tweaks %}
<html>
<head>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <title>
        Inicio de sesion
    </title>
</head>
<body>
    <h1>
        Inciar sesion
    </h1>
    <div class="container">
        <form action="{% url 'article:iniciar_sesion' %}" method="post">
            {% csrf_token %} 
            <fieldset>
            <div class="form-group">
              <label for="exampleInputUser">Usuario</label>
              <input type="text" name="username" class="form-control" id="exampleInputUser" placeholder="Ingrese un nombre">
            </div>
            <div class="form-group">
                <label for="exampleInputPassword1">Contraseña</label>
                <input type="password" name="password" class="form-control" id="exampleInputPassword1" placeholder="Ingrese una contraseña">
              </div>
        </fieldset>
        <br>
        <button type="submit" class="btn btn-primary">Enviar</button>
        </form>
        </div>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
</body>

</html>

article/templates/article/registro.html
{% load widget_tweaks %}
<html>
<head>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <title>
        Registro de usuario
    </title>
</head>
<body>
    <header>
        <h1>
            Registro de usuario
        </h1>
    </header>
        <div class="container">
            <form action="{% url 'article:registro'%}" method="post" enctype="multipart/form-data">
                {% csrf_token %} 
                {% for fields in form %}
                    <p>{{ fields.label }}</p>
                    <p>{{ fields|add_class:"form_control"}}</p>
                {% endfor %}
                <input type="text" name="photo"/>
                <button type="submit" class="btn btn-primary">Enviar</button>
              </form>
          </div>

    <main>
    </main>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

</body>
</html>

article/templates/article/registro_exitoso.html
<html>
<head>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <title>
        Se registró
    </title>
</head>
<body>

    <h1>Nombre: {{name}} </h1>
    <h1>Contraseña: {{password}}</h1>
    <h1>Correo: {{correo}}</h1>
    <img src="{{image.image.url}}" alt="{{image.name}}">

    <h2>Si sus datos son los siguientes, se registró perfectamente</h2>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

</body>
</html>

article/templates/article/ver_articulo.html
<head>
    <title>
        Ver articulo
    </title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
</head>

<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
          <a class="navbar-brand" href="{% url 'article:index' %}">Hackers blog</a>
          <button
            class="navbar-toggler"
            type="button"
            data-toggle="collapse"
            data-target="#navbarNavDropdown"
            aria-controls="navbarNavDropdown"
            aria-expanded="false"
            aria-label="Toggle navigation"
          >
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav">
              <li class="nav-item active">
                <a class="nav-link" href="#"
                  >Estas viendo el siguiente articulo
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">Sesión de {{ user.get_username }} </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#"></a>
              </li>
            </ul>
          </div>
        </nav>
      </header>
      <br>
    <main>
        <div class="container">
            <div class="card text-white bg-success mb-3" style="max-width: 18rem;">
                <div class="card-header"> <img src="{{articulo.image}}" alt="fotico" class="img-thumbnail"></div>
             <div class="card-body">
                 <h5 class="card-title">{{articulo.title}}</h5>
                 <p class="card-text">{{articulo.text}}</p>
            </div>
          </div>
        
        <div class="card text-white bg-success mb-3" style="max-width: 18rem;">
            <div class="card-body">
              <h5 class="card-title">Publicado por: {{articulo.author_fk.user.username}}</h5>
              <p class="card-text">Fecha de publicación: {{articulo.date}}</p>
              <span>Numero de hearts: {{articulo.hearts}}</span>
          </div>
        </div>
    </div>
        <br><br>
        <div class="container">
            <form method="post" name="texto" cols="50" action="{% url 'article:ver_articulo' articulo.id %}">
                {% csrf_token %} 
                <h1>Sección de comentarios</h1>
                 <textarea name="texto" cols="50">
                </textarea>
                <button type="submit" class="btn btn-primary">Enviar comentario</button>
            </form>
        </div>
        <div class="container">
            {% for comment in comentarios %}
                 <div class="card text-white bg-success mb-3" style="max-width: 18rem;">
                    <div class="card-body">
                        <h5 class="card-title">Publicado por: {{comment.author_fk.user.username}}</h5>
                        <p class="card-text">{{comment.text}}</p>
                        <textarea name="texto-{{comment.id}}" cols="20" style="position: relative; left:18em">
                        </textarea>
                    </div>
                </div>
            {% endfor %}
        </div>
    </main>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

</body>